config/routes.rb
Rails.application.routes.draw do
    root 'welcome#home'
  get 'about', to: 'welcome#about'
  resources :hospitals
  resources :studies
  resources :tours
  resources :lists
  resources :homepage

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



  resources :articles
  resources :messages, only: [:new, :create]

  get 'signup', to: "users#new"
  resources :users, except: [:new]
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, uniqueness: { case_sensitive: false }, 
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You need to be logged in to contact us"
      redirect_to signup_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Your Message was sent successfully"
      redirect_to hospitals_path(@hospitals)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Your Message was successfully updated"
      redirect_to hospitals_path(@article)
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:danger] = " Message was successfully deleted"
    redirect_to articles_path(@article)
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, :phone, :sender, :email, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:danger] = "You can only edit or delete your own Message"
      redirect_to hospitals_index
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was updated successfully"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  def index
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Logged in successfully"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with the login information"
      render 'new'
    end    
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to root_path    
  end
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  def index
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to German Medical Center #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by user have been deleted"
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:danger] = "You can only edit your own account"
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? && !current_user.admin?
      flash[:danger] = "You are welcome"
      redirect_to root_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
    redirect_to homepage_index_path if logged_in?
  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
 <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <br>
        <div class="article-sender">
          <%= link_to article.sender, article_path(article) %>
        </div>
        <div class="article-number">
          <%= link_to article.number, article_path(article) %>
        </div>
        <div class="article-email">
          <%= link_to article.email, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
            <small>Created by: <%= article.user.username if article.user %>, <%= time_ago_in_words(article.created_at) %> ago,
                  last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
        <% if article.categories.any? %>
          <p>Categories: <%= render article.categories %></p>
        <% end %>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <div class="article-actions">
            <%= link_to "Edit this Message", edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete this Message", article_path(article), method: :delete,
                                                data: { confirm: "Are you sure you want to delete this Message?" },
                                                class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<style>
  .container {
    width: 60%;
    background: #f5f5f5;
    border: 20px solid #337ab7;
    border-radius: 50px;

}

.center1 {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 63px;
}
.btn-primary {
    color: #754545;
    background-color: #337ab7;
    border-color: #337ab7;
}
.btn-primary:hover {
  color: orange;
}
</style>
<%= render 'shared/errors', obj: @article %>
<div class="container-fluid">
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => { class: "form-horizontal", role: "form" }) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%#= f.label :title %>
          <label>Title </label>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of Message", autofocus: true %>
        </div>
      </div>
       <div class="form-group">
        <div class="control-label col-sm-2">
          <%#= f.label :sender %>
          <label>Full Name</label>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :sender, class: "form-control", placeholder: "Your Full Name", autofocus: true %>
        </div>
      </div>



      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Your Email", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%#= f.label :description %>
          <label>Your Message </label>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Your Message" %>
        </div>
      </div>

      <div class="form-group">
        <div class="center1">
    <button class="btn btn-primary"><%= submit_tag("Send Your Message") %></button>
  </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">

    </div>
  </div>
</div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit Messages</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Messages</h1>

<div align="center">
  <%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Contact us </h1><br>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<h2 align="center">Sender: <%= @article.sender %></h2>

<div class="well col-xs-8 col-xs-offset-2">
  <% if @article.user %>
    <ul class="listing">
      <div class="row center">
        <div class="col-md-4 col-md-offset-4">
          <li>Created by:</li>
          <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
          <li class="article-title">
            <%= link_to @article.user.username, user_path(@article.user) %>
          </li>
          <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <h4 class="center description"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>
  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %></p>
  <% end %>
  <div class="article-actions">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to "Edit this Message", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete this Message", article_path(@article), method: :delete,
                                          data: { confirm: "Are you sure you want to delete this Message?" },
                                          class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "View all Messages", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/edit.html.erb
<h1 align="center">Edit category name</h1>

<%= render 'form' %>

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center">Category: <%= @category.name %></h1>

<div align="center">
  <% if logged_in? && current_user.admin? %>
    <div class="row">
      <span class="badge"><%= link_to "Edit category name", edit_category_path(@category) %></span>
    </div>
  <% end %>
  <%= will_paginate @category_articles %>
</div>
<%= render 'articles/article', obj: @category_articles %>
<div align="center">
  <%= will_paginate @category_articles %>
</div>

app/views/studies/index.html.erb
<style>
* {
  box-sizing: border-box;
}

 body {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 14px;
    line-height: 1.428571429;
    color: #333333;
    background-color: #d5e8cd;
    min-width: 500px;
}
.container {
    margin-top: 5px;
}

/* Float four columns side by side */
.column {
  float: left;
  width: 25%;
  padding: 0 10px;
}

/* Remove extra left and right margins, due to padding */
.row {
  margin: 0 -5px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive columns */


/* Style the counter cards */
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  padding: 16px;
  text-align: center;
  background-color: #f1f1f1;
}
.card:hover {
  background-color: #eabd84;
}
img {
  height: 200px;
  width: 100%;
  border-radius: 13%;
}

  h1 {
    text-align: center;
  }
  h4 {
    text-align: center;
  }
  h5 {
    text-align: right;
  }
  h2 {
    text-align: center;
  }
  p {
    text-align: right;
  }
  ul li {
    text-align: right;
    list-style-type: none;
  }
  .grid-container {
  display: grid;
  grid-gap: 20px;
  width: 100%;
  padding: 10px;
}
.grid-item {
  padding: 12px;
  font-size: 18px;
  text-align: center;
  text-align: left;
  background-color: #f5f5f5;
  border-radius: 47px;
}



.ul li  {
  text-align: center;
  display: inline-block;
  margin-left: 40px;
}

a {

  color: white;

}

a .btn:hover {
  background-color:#24333a;
}
.hos li {
  text-align: center;
}
.right li {
  text-align: left;
}
p {
  text-align: left;
}
h6 {
  text-align: center;
}
.center1 {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 63px;
}
@media screen and (max-width: 600px) {
  .column {
    width: 100%;
    display: block;
    margin-bottom: 20px;
  }
}

</style>

<div class="grid-container">
  <div class="grid-item">
    <h1>8 Steps to Study in Germany
</h1>
<ol>
  <li>Find a Study Program.</li>
  <li>Meet All Requirements.</li>
  <li>Learn The German Language.
</li>
  <li>Find Financial Resources.
</li>
  <li>Apply For Admission.
</li>
  <li>Get Your German Student Visa.</li>
  <li>Find Accommodation.</li>
  <li>Enroll At Your University.</li>

</ol>
   <div class="center1">
    <button class="btn btn-primary"><%= link_to "Contact us", new_article_path %></button>
  </div>
</div>
</div>


<h2>8 Steps to study in Germany</h2>
<p style="text-align: center">Follow these steps .</p><br><br>
<div class="container-2">
<div class="row">
  <div class="column">
    <div class="card">
      <a href="https://www.topuniversities.com/student-info/scholarship-advice/scholarships-study-germany">
      <img src="https://res.cloudinary.com/duf8tsxnt/image/upload/v1585679629/program_evhw4a.jpg"/></a>
      <h3>1- Find a Study Program.</h3>

      <a href="https://www.topuniversities.com/student-info/scholarship-advice/scholarships-study-germany"><button class=" btn btn-primary" style="width: 170px">See more information</button></a>
    </div>
  </div>

  <div class="column">
    <div class="card"><a href="https://www2.daad.de/deutschland/studienangebote/international-programmes/en/">
      <img src="https://res.cloudinary.com/duf8tsxnt/image/upload/v1585679644/uni1_hcw5zq.jpg"/></a>
      <h3>2- Meet All Requirements</h3>
      <a href="https://www2.daad.de/deutschland/studienangebote/international-programmes/en/"><button class=" btn btn-primary" style="width: 170px">See more information</button></a>

    </div>
  </div>

   <div class="column">
    <div class="card"><a href="https://www.goethe-university-frankfurt.de/44341978/Welcome_to_the_International_Office_website">
      <img src="https://res.cloudinary.com/duf8tsxnt/image/upload/v1585679626/flag_kezkew.jpg"/></a>
      <h3>3- Learn The German Language</h3>
      <a href="https://www.goethe-university-frankfurt.de/44341978/Welcome_to_the_International_Office_website"><button class=" btn btn-primary" style="width: 170px">See more information</button></a>

    </div>
  </div>

   <div class="column">
    <div class="card"><a href="https://www.topuniversities.com/student-info/scholarship-advice/scholarships-study-germany">
      <img src="https://res.cloudinary.com/duf8tsxnt/image/upload/v1585679614/finance_ilvhsy.jpg"/></a>
      <h3>4- Find Financial Resources</h3>
      <a href="https://www.topuniversities.com/student-info/scholarship-advice/scholarships-study-germany"><button class=" btn btn-primary" style="width: 170px">See more information</button></a>

    </div>
  </div>

</div> <br><br>
<div class="container-2">
  <div class="row">
  <div class="column">
    <div class="card">
      <a href="https://www.hochschulstart.de/index.php">
      <img src="https://res.cloudinary.com/duf8tsxnt/image/upload/v1585679644/uni2_hmsqkm.jpg"/></a>
      <h3>5- Apply For Admission.</h3>

      <a href="https://www.hochschulstart.de/index.php"><button class=" btn btn-primary" style="width: 170px">See more information</button></a>
    </div>
  </div>

  <div class="column">
    <div class="card"><a href="https://www2.daad.de/deutschland/studienangebote/international-programmes/en/">
      <img src="https://res.cloudinary.com/duf8tsxnt/image/upload/v1585679826/passport.jpg"/></a>
      <h3>6- Get Your German Student Visa</h3>
      <a href="https://www2.daad.de/deutschland/studienangebote/international-programmes/en/"><button class=" btn btn-primary" style="width: 170px">See more information</button></a>

    </div>
  </div>

   <div class="column">
    <div class="card"><a href="https://www.topuniversities.com/student-info/careers-advice/how-work-germany-during-or-after-your-studies">
      <img src="https://res.cloudinary.com/duf8tsxnt/image/upload/v1585679625/flat_yzgt8p.jpg"/></a>
      <h3>7- Find Accommodation</h3>
      <a href="https://www.topuniversities.com/student-info/careers-advice/how-work-germany-during-or-after-your-studies"><button class=" btn btn-primary" style="width: 170px">See more information</button></a>

    </div>
  </div>

   <div class="column">
    <div class="card"><a href="https://www.topuniversities.com/student-info/scholarship-advice/scholarships-study-germany">
      <img src="https://res.cloudinary.com/duf8tsxnt/image/upload/v1585679642/univer_vjw4rs.jpg"/></a>
      <h3>8- Enroll At Your University</h3>
      <a href="https://www.topuniversities.com/student-info/scholarship-advice/scholarships-study-germany"><button class=" btn btn-primary" style="width: 170px">See more information</button></a>

    </div>
  </div>
</div> <br><br>
<div class="grid-container">
  <div class="grid-item">
    <h1>8 Steps to Study in Germany
</h1>
<ol>
  <li>Find a Study Program.</li>
  <li>Meet All Requirements.</li>
  <li>Learn The German Language.
</li>
  <li>Find Financial Resources.
</li>
  <li>Apply For Admission.
</li>
  <li>Get Your German Student Visa.</li>
  <li>Find Accommodation.</li>
  <li>Enroll At Your University.</li>

</ol>
   <div class="center1">
    <button class="btn btn-primary"><%= link_to "Contact us", new_article_path %></button>
  </div>
</div>
</div>


<div class="grid-container">
  <div class="grid-item">
   <h1>1. Find a Study Program
</h1>
<p>Finding a university and choosing a study program that suits your interests is the first step to planning your studies in Germany.</p><br>


   <div class="center1">
    <button class="btn btn-primary"><%= link_to "Contact us", new_article_path %></button>
  </div>
</div>
</div><br>

<div class="grid-container">
  <div class="grid-item">
    <h1>2. Meet All Requirements</h1>
    <h6>(Two weeks before the application is opened)</h6>

<p>Now that you have decided what university and what study program you want to attend you must check out all the requirements. For this purpose, you check the university website and their admission requirements section. If there are things you don’t understand never hesitate to contact the university directly.</p>
<br>
   <div class="center1">
    <button class="btn btn-primary"><%= link_to "Contact us", new_article_path %></button>
  </div>
</div>
</div><br>

<div class="grid-container">
  <div class="grid-item">
    <h1>
3. Learn The German Language</h1>
    <h6>(Start learning it 6 months before the application or the course commencing)</h6>

<p>Now that you have decided what university and what study program you want to attend you must check out all the requirements. For this purpose, you check the university website and their admission requirements section. If there are things you don’t understand never hesitate to contact the university directly.</p>
<br>

   <div class="center1">
    <button class="btn btn-primary"><%= link_to "Contact us", new_article_path %></button>
  </div>
</div>
</div><br>

<div class="grid-container">
  <div class="grid-item">
    <h1>4. Find Financial Resources
</h1>
    <h6>(at least two weeks before you apply for a German student visa)</h6>

<p>The next step is making sure you have the required financial means to live and study in Germany. Under the current law, every foreign non-EU or non-EEA student must have proper financial means to finance their stay in Germany during their studies..</p>
<p>An international student in Germany must possess a minimum of €10,236 which is estimated to be enough for a student to cover the cost of living for the first year of his studies. This amount of money needs to be deposited into a German blocked bank account.</p>
<br>

   <div class="center1">
    <button class="btn btn-primary"><%= link_to "Contact us", new_article_path %></button>
  </div>
</div>
</div><br>

<div class="grid-container">
  <div class="grid-item">
    <h1>
5. Apply For Admission</h1>
    <h6>(As soon as you complete requirements)

</h6>

<p>Now that you have decided what university and what study program you want to attend you must check out all the requirements. For this purpose, you check the university website and their admission requirements section. If there are things you don’t understand never hesitate to contact the university directly.</p>
<br>

   <div class="center1">
    <button class="btn btn-primary"><%= link_to "Contact us", new_article_path %></button>
  </div>
</div>
</div><br>
<div class="grid-container">
  <div class="grid-item">
    <h1>6. Get Your German Student Visa</h1>
    <h6>(As soon as you receive the admission letter)

</h6>

<p></p>
<br>

   <div class="center1">
    <button class="btn btn-primary"><%= link_to "Contact us", new_article_path %></button>
  </div>
</div>
</div><br>

<div class="grid-container">
  <div class="grid-item">
    <h1>7. Find Accommodation</h1>
    <h6>(If possible two weeks before your landing in Germany)</h6>

<p></p>
<br>

   <div class="center1">
    <button class="btn btn-primary"><%= link_to "Contact us", new_article_path %></button>
  </div>
</div>
</div><br>

<div class="grid-container">
  <div class="grid-item">
    <h1>8. Enroll At Your University</h1>
    <h6>(First week after arriving in Germany)</h6>

<p>The final step to officially be given a place at the university of your choice is to enroll in the course at which you have been admitted. In this sense, the enrollment process takes you from a successful applicant to a registered student in Germany.

The public higher education in Germany is offered for free, but you will still have to pay a registration fee which ranges somewhat between €150 and €250. Additionally, you will have to pay for your Semester ticket to use public transportation free of charge for 6 months.

To enroll at your university course in Germany you need to personally appear at the administration office of your university and submit the following documents:</p>
<br>
<ol>
  <li>Your valid passport</li>
  <li>A passport photo</li>
  <li>Your Visa or Residence Permit</li>
  <li>Completed and signed Application Form</li>
  <li>Degree qualifications (original documents or certified copies)</li>
  <li>The Letter of Admission</li>
  <li>Proof of health insurance in Germany </li>
  <li>The payment fee receipt</li>

</ol>
<a href="https://www.studying-in-germany.org/requirements-to-study-in-germany-for-indian-students/"><p>Check out all the requirements</p></a>
   <div class="center1">
    <button class="btn btn-primary"><%= link_to "Contact us", new_article_path %></button>
  </div>
</div>
</div><br>

app/views/users/_form.html.erb
<style>
  #btn a {
    color: white;
    padding: 10px 16px;
    font-size: 18px;
    line-height: 1.3333333;
    border-radius: 6px;
  }

</style>
<%= render 'shared/errors', obj: @user %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@user, :html => { class: "form-horizontal", role: "form" }) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :username %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :password %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-8 col-sm-offset-2">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update your account", class: "btn btn-primary btn-lg") %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
       <%#= link_to "Cancel request and return to articles listing", hospitals_path %>
       <P> Click to login if you have already Account</P>
       <button class="btn btn-primary" id="btn"><%= link_to "Log in", login_path %></button>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1 align="center">Sign up for German Medical Center </h1>

<%= render 'form' %>