config/routes.rb
Rails.application.routes.draw do
    root 'welcome#home'
  get 'about', to: 'welcome#about'
  resources :hospitals
  resources :studies
  resources :tours
  resources :lists
  resources :homepage

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



  resources :articles
  resources :messages, only: [:new, :create]

  get 'signup', to: "users#new"
  resources :users, except: [:new]
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, uniqueness: { case_sensitive: false }, 
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Your Message was sent successfully"
      redirect_to hospitals_path(@hospitals)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Your Message was successfully updated"
      redirect_to hospitals_path(@article)
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:danger] = " Message was successfully deleted"
    redirect_to articles_path(@article)
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, :phone, :sender, :email, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:danger] = "You can only edit or delete your own Message"
      redirect_to hospitals_index
    end
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  def index
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Logged in successfully"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with the login information"
      render 'new'
    end    
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to root_path    
  end
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  def index
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to German Medical Center #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by user have been deleted"
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:danger] = "You can only edit your own account"
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? && !current_user.admin?
      flash[:danger] = "You are welcome"
      redirect_to root_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
    redirect_to homepage_index_path if logged_in?
  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/layouts/_footer.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>

.fa {
  padding: 20px;
  font-size: 30px;
  width: 70px;
  text-align: center;
  text-decoration: none;
  margin: 5px 2px;
}

.fa:hover {
    opacity: 0.7;
}

.fa-facebook {
  background: #3B5998;
  color: white;
  border-radius: 12px;
}

.fa-twitter {
  background: #55ACEE;
  color: white;
  border-radius: 12px;
}

.fa-google {
  background: #dd4b39;
  color: white;
  border-radius: 12px;
}


.fa-youtube {
  background: #bb0000;
  color: white;
  border-radius: 12px;
}




.container-1{
  margin-left: auto;
  margin-right: auto;
  text-align: center;
}

a {
  margin-left: 5px;
}
.footer {
   position: fixed;
   left: 0;
   bottom: 0;
   color: white;
   text-align: center;
   bottom:  80px;

}
.whats {
      background-color: #34ca62;
      width: 125px;
}


/* Mobile - Center align footer content */


</style>
  </head>
<body>

<footer>
  <div class="container3 text-center">
      <h5 style="text-align: center" >Copyright &copy; German Medical Center Berlin Germany</h5>
      <h5 style="text-align: center">Monther Al Gbawi</h5>
      <br>
    </div>
  <div class="container-1">

  <a href="https://www.facebook.com/" class="fa fa-facebook"></a>

  <a href="https://www.twitter.com" class="fa fa-twitter"></a>
   <a href="https://www.youtube.com" class="fa fa-youtube">

  <a href="https://www.google.com" class="fa fa-google"></a>
</div>

</footer>
<footer class="footer">
  <button class="whats">00491629014596
  <i class="fa fa-whatsapp my-float" style="padding: 0px"></i>
</button>
</footer>
</body>
</html>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">
          &#215;
        </a>
        <%= msg %>
      </div>
    <% end %>  
  </div>
</div>

app/views/layouts/_navigation.html.erb
<style>
  .navbar-default .navbar-nav > li > a {
    color: white;
    text-align: left;
    margin-right: 17px;
    padding-right: 0;

}
.navbar-default {
    background-color: #1d2125;
    border-color: #581616;
}
.navbar-default .navbar-nav > li > a:hover {
 color: orange;
}
.nav li {
  margin-left: 2px;

}

.container-fluid {
    margin-right: auto;
    margin-left: auto;
    padding-left: 3px;
    padding-right: 0px;
}

</style>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "German Visa", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav" style="float: left" >
        <li><%= link_to "Hospitals & Treatment", hospitals_path %></li>




        <li><%= link_to "Study in Germany", studies_path %></li>
        <li><%= link_to "Universities in Germany", lists_path %></li>
        <li><%= link_to "Tours in Germany ", tours_path %>
          <li><%= link_to "Team & Contacts ", about_path %>

            <li><%#= link_to "Contact us", new_article_path %></li>

        </li><ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "(admin)" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%#= link_to "Edit your profile", edit_user_path(current_user) %></li>
              <li><%#= link_to "View your profile", user_path(current_user) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
      </ul>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin Dashboard <span class="caret" style="color: white"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Categories", categories_path %></li>
            <% Category.all.each do |category| %>
              <li><%= link_to category.name, category_path(category) %></li>

            <% end %>
            <% if logged_in? && current_user.admin? %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Messages", articles_path %></li>
              <li><%= link_to "Create New Category", new_category_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>German Visa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <style>
  body {
    background-color: #d5e8cd;
  }

</style>

  <body>

    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%#= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this article from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>